### ISSUE TITLE
RemovedInDjango40Warning

### ISSUE THREAD

**Issue by hanckmann** [timonweb/django-clearcache#6]
The library currently triggers the following warnings in my tests:

../usr/local/lib/python3.8/site-packages/clearcache/urls.py:5
  /usr/local/lib/python3.8/site-packages/clearcache/urls.py:5: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    url(r'$', ClearCacheAdminView.as_view(), name="clearcache_admin"),

If you need more info, I will be happy to help.

Thanks for building this awesome Django app!

**Comment by timonweb** [comment]
Done, thanks for the report!
