### ISSUE TITLE
Django 3.2 Support

### ISSUE THREAD

**Issue by jhnbkr** [timonweb/django-clearcache#7]
Django 3.2 has entered the release candidate phase and is expected by early April.

I am not intimately familiar with the inner workings of `django-clearcache` and cannot say if there are any compatibility issues.

Here is the working list of [backwards incompatible changes](https://docs.djangoproject.com/en/3.2/releases/3.2/#backwards-incompatible-changes-in-3-2).

**Comment by jhnbkr** [comment]
[Pull request #8](https://github.com/timonweb/django-clearcache/pull/8)

**Comment by timonweb** [comment]
Done, thanks for the PR!
